sudo: required
dist: trusty
language: node_js
node_js:
  - '9.6'

addons:
  chrome: stable

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9876 http://localhost &
before_script:
  - npm install -g karma
  - npm install
  - ng build

script: ng test --karma-config ./karma.conf.js --watch=false
